### ISSUE TITLE
Develop a CartoJSS serializer

### ISSUE THREAD

**Issue by Jesus89** [CartoDB/cartodb.js#1832]
Writing CartoCSS in ES5 is a bit difficult since it has no [backtick strings](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals). So we want to allow CARTO.js users to write JSON CartoCSS or "CartoJSS":

For example, this CartoJSS:
```javascript
{
  '#continent_points': {
    'marker-fill-opacity': 0.9,
    'marker-line-color': '#FFF',
    'marker-placement': 'point',
    'marker-allow-overlap': true,
    '[continent="Africa"]': {
      'marker-fill': '#A6CEE3'
    },
    '[continent="Antarctica"]': {
      'marker-fill': '#1F78B4'
    }
  }
}
```

will be converted to this CartoCSS:

```css
#continent_points {
  marker-fill-opacity: 0.9;
  marker-line-color: #FFF;
  marker-placement: point;
  marker-allow-overlap: true;
  [continent="Africa"] {
    marker-fill: #A6CEE3;
  }
  [continent="Antarctica"] {
    marker-fill: #1F78B4;
  }
}
```

Sources:
* https://carto.com/docs/carto-engine/cartocss/best-practices/

cc @makella
